
name: deploy to Github Pages
on:
  # schedule:
  #   - cron: '0 2 * * *'

  # Runs on pushes targeting the default branch
  workflow_run:
    workflows: ["test the app"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  PROJECT_NAME: Dashboard/Dashboard.csproj

jobs:
  deploy-to-github-pages:
  
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
        
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools 

    - name: installing package PublishSPAforGitHubPages.Build 
      run: dotnet add ${{ env.PROJECT_NAME }} package PublishSPAforGitHubPages.Build
      
    # publishes project to the release folder
    - name: Publish .Net Core Project
      run: dotnet publish ./${{ env.PROJECT_NAME }} -c Release -o release --nologo -p:GHPages=true
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUb_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot