
name: deploy to Github Pages
on:
  # schedule:
  #   - cron: '0 2 * * *'

  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  PROJECT_NAME: Dashboard/Dashboard.csproj

jobs:
  deploy-to-github-pages:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with the dotnet CLI
      run: dotnet test --no-build
        
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools 

    - name: installing package PublishSPAforGitHubPages.Build 
      run: dotnet add ${{ env.PROJECT_NAME }} package PublishSPAforGitHubPages.Build
      
    # publishes project to the release folder
    - name: Publish .Net Core Project
      run: dotnet publish ./${{ env.PROJECT_NAME }} -c Release -o release --nologo -p:GHPages=true
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUb_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot