
name: test the app
on:

  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
  
      - name: Install dependencies
        run: dotnet restore
     
      - name: Build
        run: dotnet build --no-restore

      - name: Test with the dotnet CLI
        run: dotnet test --no-build
        